# ansible-playbook playbook_f5_change-node.yml --vault-id prod@vault_key --extra-vars "state=disabled"
---

- name: Check node info
  hosts: nj-tel-lb02.example.com

  tasks:
    - name: Bring node online
      bigip_node:
        state: "{{ state }}"
        name: 192.168.20.44
        provider:
          server: nj-tel-lb02.example.com
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          validate_certs: no
      delegate_to: localhost
      register: cli_result

    - name: Spit out that stuff
      debug: var=cli_result