---
- name: Task 1 of 2 - Get the running-config
  nxos_command:
    commands:
      - term len 0
      - show running-config | begin ^version
  register: cli_results

- name: Task 2 of 2 - Save the running config to ansible server
  copy:
    content: "{{ cli_results.stdout[1] }}"
    dest: "{{ backup_dir }}/{{ inventory_hostname }}.cfg"